import 'package:collection/collection.dart' show IterableExtension;
import 'package:json_annotation/json_annotation.dart';

@JsonEnum(fieldRename: FieldRename.snake)
enum PlaceType {
  /// Automotive
  carDealer('car_dealer'),
  carRental('car_rental'),
  carRepair('car_repair'),
  carWash('car_wash'),
  electricVehicleChargingStation('electric_vehicle_charging_station'),
  gasStation('gas_station'),
  parking('parking'),
  restStop('rest_stop'),

  /// Business
  corporateOffice('corporate_office'),
  farm('farm'),
  ranch('ranch'),

  /// Culture
  artGallery('art_gallery'),
  artStudio('art_studio'),
  auditorium('auditorium'),
  culturalLandmark('cultural_landmark'),
  historicalPlace('historical_place'),
  monument('monument'),
  museum('museum'),
  performingArtsTheater('performing_arts_theater'),
  sculpture('sculpture'),

  /// Education
  library('library'),
  preschool('preschool'),
  primarySchool('primary_school'),
  school('school'),
  secondarySchool('secondary_school'),
  university('university'),

  /// Entertainment and Recreation
  adventureSportsCenter('adventure_sports_center'),
  amphitheatre('amphitheatre'),
  amusementCenter('amusement_center'),
  amusementPark('amusement_park'),
  aquarium('aquarium'),
  banquetHall('banquet_hall'),
  barbecueArea('barbecue_area'),
  botanicalGarden('botanical_garden'),
  bowlingAlley('bowling_alley'),
  casino('casino'),
  childrensCamp('childrens_camp'),
  comedyClub('comedy_club'),
  communityCenter('community_center'),
  concertHall('concert_hall'),
  conventionCenter('convention_center'),
  culturalCenter('cultural_center'),
  cyclingPark('cycling_park'),
  danceHall('dance_hall'),
  dogPark('dog_park'),
  eventVenue('event_venue'),
  ferrisWheel('ferris_wheel'),
  garden('garden'),
  hikingArea('hiking_area'),
  historicalLandmark('historical_landmark'),
  internetCafe('internet_cafe'),
  karaoke('karaoke'),
  marina('marina'),
  movieRental('movie_rental'),
  movieTheater('movie_theater'),
  nationalPark('national_park'),
  nightClub('night_club'),
  observationDeck('observation_deck'),
  offRoadingArea('off_roading_area'),
  operaHouse('opera_house'),
  park('park'),
  philharmonicHall('philharmonic_hall'),
  picnicGround('picnic_ground'),
  planetarium('planetarium'),
  plaza('plaza'),
  rollerCoaster('roller_coaster'),
  skateboardPark('skateboard_park'),
  statePark('state_park'),
  touristAttraction('tourist_attraction'),
  videoArcade('video_arcade'),
  visitorCenter('visitor_center'),
  waterPark('water_park'),
  weddingVenue('wedding_venue'),
  wildlifePark('wildlife_park'),
  wildlifeRefuge('wildlife_refuge'),
  zoo('zoo'),

  /// Facilities
  publicBath('public_bath'),
  publicBathroom('public_bathroom'),
  stable('stable'),

  /// Finance
  accounting('accounting'),
  atm('atm'),
  bank('bank'),

  /// Food and Drink
  acaiShop('acai_shop'),
  afghaniRestaurant('afghani_restaurant'),
  africanRestaurant('african_restaurant'),
  americanRestaurant('american_restaurant'),
  asianRestaurant('asian_restaurant'),
  bagelShop('bagel_shop'),
  bakery('bakery'),
  bar('bar'),
  barAndGrill('bar_and_grill'),
  barbecueRestaurant('barbecue_restaurant'),
  brazilianRestaurant('brazilian_restaurant'),
  breakfastRestaurant('breakfast_restaurant'),
  brunchRestaurant('brunch_restaurant'),
  buffetRestaurant('buffet_restaurant'),
  cafe('cafe'),
  cafeteria('cafeteria'),
  candyStore('candy_store'),
  catCafe('cat_cafe'),
  chineseRestaurant('chinese_restaurant'),
  chocolateFactory('chocolate_factory'),
  chocolateShop('chocolate_shop'),
  coffeeShop('coffee_shop'),
  confectionery('confectionery'),
  deli('deli'),
  dessertRestaurant('dessert_restaurant'),
  dessertShop('dessert_shop'),
  diner('diner'),
  dogCafe('dog_cafe'),
  donutShop('donut_shop'),
  fastFoodRestaurant('fast_food_restaurant'),
  fineDiningRestaurant('fine_dining_restaurant'),
  foodCourt('food_court'),
  frenchRestaurant('french_restaurant'),
  greekRestaurant('greek_restaurant'),
  hamburgerRestaurant('hamburger_restaurant'),
  iceCreamShop('ice_cream_shop'),
  indianRestaurant('indian_restaurant'),
  indonesianRestaurant('indonesian_restaurant'),
  italianRestaurant('italian_restaurant'),
  japaneseRestaurant('japanese_restaurant'),
  juiceShop('juice_shop'),
  koreanRestaurant('korean_restaurant'),
  lebaneseRestaurant('lebanese_restaurant'),
  mealDelivery('meal_delivery'),
  mealTakeaway('meal_takeaway'),
  mediterraneanRestaurant('mediterranean_restaurant'),
  mexicanRestaurant('mexican_restaurant'),
  middleEasternRestaurant('middle_eastern_restaurant'),
  pizzaRestaurant('pizza_restaurant'),
  pub('pub'),
  ramenRestaurant('ramen_restaurant'),
  restaurant('restaurant'),
  sandwichShop('sandwich_shop'),
  seafoodRestaurant('seafood_restaurant'),
  spanishRestaurant('spanish_restaurant'),
  steakHouse('steak_house'),
  sushiRestaurant('sushi_restaurant'),
  teaHouse('tea_house'),
  thaiRestaurant('thai_restaurant'),
  turkishRestaurant('turkish_restaurant'),
  veganRestaurant('vegan_restaurant'),
  vegetarianRestaurant('vegetarian_restaurant'),
  vietnameseRestaurant('vietnamese_restaurant'),
  wineBar('wine_bar'),

  /// Geographical Areas
  administrativeAreaLevel1('administrative_area_level_1'),
  administrativeAreaLevel2('administrative_area_level_2'),
  country('country'),
  locality('locality'),
  postalCode('postal_code'),
  schoolDistrict('school_district'),

  /// Government
  ityHall('ity_hall'),
  courthouse('courthouse'),
  embassy('embassy'),
  fireStation('fire_station'),
  governmentOffice('government_office'),
  localGovernmentOffice('local_government_office'),

  /// (Japan only)
  neighborhoodPoliceStation('neighborhood_police_station'),
  police('police'),
  postOffice('post_office'),

  /// Health and Wellness
  chiropractor('chiropractor'),
  dentalClinic('dental_clinic'),
  dentist('dentist'),
  doctor('doctor'),
  drugstore('drugstore'),
  hospital('hospital'),
  massage('massage'),
  medicalLab('medical_lab'),
  pharmacy('pharmacy'),
  physiotherapist('physiotherapist'),
  sauna('sauna'),
  skinCareClinic('skin_care_clinic'),
  spa('spa'),
  tanningStudio('tanning_studio'),
  wellnessCenter('wellness_center'),
  yogaStudio('yoga_studio'),

  /// Housing
  apartmentBuilding('apartment_building'),
  apartmentComplex('apartment_complex'),
  condominiumComplex('condominium_complex'),
  housingComplex('housing_complex'),

  /// Lodging
  bedAndBreakfast('bed_and_breakfast'),
  budgetJapaneseInn('budget_japanese_inn'),
  campground('campground'),
  campingCabin('camping_cabin'),
  cottage('cottage'),
  extendedStayHotel('extended_stay_hotel'),
  farmstay('farmstay'),
  guestHouse('guest_house'),
  hostel('hostel'),
  hotel('hotel'),
  inn('inn'),
  japaneseInn('japanese_inn'),
  lodging('lodging'),
  mobileHomePark('mobile_home_park'),
  motel('motel'),
  privateGuestRoom('private_guest_room'),
  resortHotel('resort_hotel'),
  rvPark('rv_park'),

  /// Natural Features
  beach('beach'),

  /// Places of Worship
  church('church'),
  hinduTemple('hindu_temple'),
  mosque('mosque'),
  synagogue('synagogue'),

  /// Services
  astrologer('astrologer'),
  barberShop('barber_shop'),
  beautician('beautician'),
  beautySalon('beauty_salon'),
  bodyArtService('body_art_service'),
  cateringService('catering_service'),
  cemetery('cemetery'),
  childCareAgency('child_care_agency'),
  consultant('consultant'),
  courierService('courier_service'),
  electrician('electrician'),
  florist('florist'),
  foodDelivery('food_delivery'),
  footCare('foot_care'),
  funeralHome('funeral_home'),
  hairCare('hair_care'),
  hairSalon('hair_salon'),
  insuranceAgency('insurance_agency'),
  laundry('laundry'),
  lawyer('lawyer'),
  locksmith('locksmith'),
  makeupArtist('makeup_artist'),
  movingCompany('moving_company'),
  nailSalon('nail_salon'),
  painter('painter'),
  plumber('plumber'),
  psychic('psychic'),
  realEstateAgency('real_estate_agency'),
  roofingContractor('roofing_contractor'),
  storage('storage'),
  summerCampOrganizer('summer_camp_organizer'),
  tailor('tailor'),
  telecommunicationsServiceProvider('telecommunications_service_provider'),
  tourAgency('tour_agency'),
  touristInformationCenter('tourist_information_center'),
  travelAgency('travel_agency'),
  veterinaryCare('veterinary_care'),

  /// Shopping
  asianGroceryStore('asian_grocery_store'),
  autoPartsStore('auto_parts_store'),
  bicycleStore('bicycle_store'),
  bookStore('book_store'),
  butcherShop('butcher_shop'),
  cellPhoneStore('cell_phone_store'),
  clothingStore('clothing_store'),
  convenienceStore('convenience_store'),
  departmentStore('department_store'),
  discountStore('discount_store'),
  electronicsStore('electronics_store'),
  foodStore('food_store'),
  furnitureStore('furniture_store'),
  giftShop('gift_shop'),
  groceryStore('grocery_store'),
  hardwareStore('hardware_store'),
  homeGoodsStore('home_goods_store'),
  homeImprovementStore('home_improvement_store'),
  jewelryStore('jewelry_store'),
  liquorStore('liquor_store'),
  market('market'),
  petStore('pet_store'),
  shoeStore('shoe_store'),
  shoppingMall('shopping_mall'),
  sportingGoodsStore('sporting_goods_store'),
  store('store'),
  supermarket('supermarket'),
  warehouseStore('warehouse_store'),
  wholesaler('wholesaler'),

  /// Sports
  arena('arena'),
  athleticField('athletic_field'),
  fishingCharter('fishing_charter'),
  fishingPond('fishing_pond'),
  fitnessCenter('fitness_center'),
  golfCourse('golf_course'),
  gym('gym'),
  iceSkatingRink('ice_skating_rink'),
  playground('playground'),
  skiResort('ski_resort'),
  sportsActivityLocation('sports_activity_location'),
  sportsClub('sports_club'),
  sportsCoaching('sports_coaching'),
  sportsComplex('sports_complex'),
  stadium('stadium'),
  swimmingPool('swimming_pool'),

  /// Transportation
  airport('airport'),
  airstrip('airstrip'),
  busStation('bus_station'),
  busStop('bus_stop'),
  ferryTerminal('ferry_terminal'),
  heliport('heliport'),
  internationalAirport('international_airport'),
  lightRailStation('light_rail_station'),
  parkAndRide('park_and_ride'),
  subwayStation('subway_station'),
  taxiStand('taxi_stand'),
  trainStation('train_station'),
  transitDepot('transit_depot'),
  transitStation('transit_station'),
  truckStop('truck_stop'),

  /// Table B values may be returned as part of a Place Autocomplete (New) response.
  administrativeAreaLevel3('administrative_area_level_3'),
  administrativeAreaLevel4('administrative_area_level_4'),
  administrativeAreaLevel5('administrative_area_level_5'),
  administrativeAreaLevel6('administrative_area_level_6'),
  administrativeAreaLevel7('administrative_area_level_7'),
  archipelago('archipelago'),
  colloquialArea('colloquial_area'),
  continent('continent'),
  establishment('establishment'),
  finance('finance'),
  floor('floor'),
  food('food'),
  generalContractor('general_contractor'),
  geocode('geocode'),
  health('health'),
  intersection('intersection'),
  landmark('landmark'),
  naturalFeature('natural_feature'),
  neighborhood('neighborhood'),
  placeOfWorship('place_of_worship'),
  plusCod('plus_cod'),
  pointOfInterest('point_of_interest'),
  political('political'),
  postBox('post_box'),
  postalCodePrefix('postal_code_prefix'),
  postalCodeSuffix('postal_code_suffix'),
  postalTown('postal_town'),
  premise('premise'),
  room('room'),
  route('route'),
  streetAddress('street_address'),
  streetNumber('street_number'),
  sublocality('sublocality'),
  sublocalityLevel1('sublocality_level_1'),
  sublocalityLevel2('sublocality_level_2'),
  sublocalityLevel3('sublocality_level_3'),
  sublocalityLevel4('sublocality_level_4'),
  sublocalityLevel5('sublocality_level_5'),
  subpremise('subpremise'),
  townSquare('town_square'),
  ;

  /// Automotive Types: https://developers.google.com/maps/documentation/places/web-service/place-types#automotive
  static const List<PlaceType> automotiveTypes = [
    carDealer,
    carRental,
    carRepair,
    carWash,
    electricVehicleChargingStation,
    gasStation,
    parking,
    restStop,
  ];

  /// Business Types: https://developers.google.com/maps/documentation/places/web-service/place-types#business
  static const List<PlaceType> businessTypes = [
    corporateOffice,
    farm,
    ranch,
  ];

  /// Culture Types: https://developers.google.com/maps/documentation/places/web-service/place-types#culture
  static const List<PlaceType> cultureTypes = [
    artGallery,
    artStudio,
    auditorium,
    culturalLandmark,
    historicalPlace,
    monument,
    museum,
    performingArtsTheater,
    sculpture,
  ];

  /// Education Types: https://developers.google.com/maps/documentation/places/web-service/place-types#education
  static const List<PlaceType> educationTypes = [
    library,
    preschool,
    primarySchool,
    school,
    secondarySchool,
    university,
  ];

  /// Entertainment and Recreation Types: https://developers.google.com/maps/documentation/places/web-service/place-types#entertainment-and-recreation
  static const List<PlaceType> entertainmentAndRecreationTypes = [
    adventureSportsCenter,
    amphitheatre,
    amusementCenter,
    amusementPark,
    aquarium,
    banquetHall,
    barbecueArea,
    botanicalGarden,
    bowlingAlley,
    casino,
    childrensCamp,
    comedyClub,
    communityCenter,
    concertHall,
    conventionCenter,
    culturalCenter,
    cyclingPark,
    danceHall,
    dogPark,
    eventVenue,
    ferrisWheel,
    garden,
    hikingArea,
    historicalLandmark,
    internetCafe,
    karaoke,
    marina,
    movieRental,
    movieTheater,
    nationalPark,
    nightClub,
    observationDeck,
    offRoadingArea,
    operaHouse,
    park,
    philharmonicHall,
    picnicGround,
    planetarium,
    plaza,
    rollerCoaster,
    skateboardPark,
    statePark,
    touristAttraction,
    videoArcade,
    visitorCenter,
    waterPark,
    weddingVenue,
    wildlifePark,
    wildlifeRefuge,
    zoo,
  ];

  /// Facilities Types: https://developers.google.com/maps/documentation/places/web-service/place-types#facilities
  static const List<PlaceType> facilitiesTypes = [
    publicBath,
    publicBathroom,
    stable,
  ];

  /// Finance Types: https://developers.google.com/maps/documentation/places/web-service/place-types#finance
  static const List<PlaceType> financeTypes = [
    accounting,
    atm,
    bank,
  ];

  /// Food and Drink Types: https://developers.google.com/maps/documentation/places/web-service/place-types#food-and-drink
  static const List<PlaceType> foodAndDrinkTypes = [
    acaiShop,
    afghaniRestaurant,
    africanRestaurant,
    americanRestaurant,
    asianRestaurant,
    bagelShop,
    bakery,
    bar,
    barAndGrill,
    barbecueRestaurant,
    brazilianRestaurant,
    breakfastRestaurant,
    brunchRestaurant,
    buffetRestaurant,
    cafe,
    cafeteria,
    candyStore,
    catCafe,
    chineseRestaurant,
    chocolateFactory,
    chocolateShop,
    coffeeShop,
    confectionery,
    deli,
    dessertRestaurant,
    dessertShop,
    diner,
    dogCafe,
    donutShop,
    fastFoodRestaurant,
    fineDiningRestaurant,
    foodCourt,
    frenchRestaurant,
    greekRestaurant,
    hamburgerRestaurant,
    iceCreamShop,
    indianRestaurant,
    indonesianRestaurant,
    italianRestaurant,
    japaneseRestaurant,
    juiceShop,
    koreanRestaurant,
    lebaneseRestaurant,
    mealDelivery,
    mealTakeaway,
    mediterraneanRestaurant,
    mexicanRestaurant,
    middleEasternRestaurant,
    pizzaRestaurant,
    pub,
    ramenRestaurant,
    restaurant,
    sandwichShop,
    seafoodRestaurant,
    spanishRestaurant,
    steakHouse,
    sushiRestaurant,
    teaHouse,
    thaiRestaurant,
    turkishRestaurant,
    veganRestaurant,
    vegetarianRestaurant,
    vietnameseRestaurant,
    wineBar,
  ];

  /// Geographical Areas Types: https://developers.google.com/maps/documentation/places/web-service/place-types#geographical-areas
  static const List<PlaceType> geographicalAreasTypes = [
    administrativeAreaLevel1,
    administrativeAreaLevel2,
    country,
    locality,
    postalCode,
    schoolDistrict,
  ];

  /// Government Types: https://developers.google.com/maps/documentation/places/web-service/place-types#government
  static const List<PlaceType> governmentTypes = [
    ityHall,
    courthouse,
    embassy,
    fireStation,
    governmentOffice,
    localGovernmentOffice,
    neighborhoodPoliceStation,
    police,
    postOffice,
  ];

  /// Health and Wellness Types: https://developers.google.com/maps/documentation/places/web-service/place-types#health-and-wellness
  static const List<PlaceType> healthAndWellnessTypes = [
    chiropractor,
    dentalClinic,
    dentist,
    doctor,
    drugstore,
    hospital,
    massage,
    medicalLab,
    pharmacy,
    physiotherapist,
    sauna,
    skinCareClinic,
    spa,
    tanningStudio,
    wellnessCenter,
    yogaStudio,
  ];

  /// Housing Types: https://developers.google.com/maps/documentation/places/web-service/place-types#housing
  static const List<PlaceType> housingTypes = [
    apartmentBuilding,
    apartmentComplex,
    condominiumComplex,
    housingComplex,
  ];

  /// Lodging Types: https://developers.google.com/maps/documentation/places/web-service/place-types#lodging
  static const List<PlaceType> lodgingTypes = [
    bedAndBreakfast,
    budgetJapaneseInn,
    campground,
    campingCabin,
    cottage,
    extendedStayHotel,
    farmstay,
    guestHouse,
    hostel,
    hotel,
    inn,
    japaneseInn,
    lodging,
    mobileHomePark,
    motel,
    privateGuestRoom,
    resortHotel,
    rvPark,
  ];

  /// Natural Features Types: https://developers.google.com/maps/documentation/places/web-service/place-types#natural-features
  static const List<PlaceType> naturalFeaturesTypes = [
    beach,
  ];

  /// Places of Worship Types: https://developers.google.com/maps/documentation/places/web-service/place-types#places-of-worship
  static const List<PlaceType> placesOfWorshipTypes = [
    church,
    hinduTemple,
    mosque,
    synagogue,
  ];

  /// Services Types: https://developers.google.com/maps/documentation/places/web-service/place-types#services
  static const List<PlaceType> servicesTypes = [
    astrologer,
    barberShop,
    beautician,
    beautySalon,
    bodyArtService,
    cateringService,
    cemetery,
    childCareAgency,
    consultant,
    courierService,
    electrician,
    florist,
    foodDelivery,
    footCare,
    funeralHome,
    hairCare,
    hairSalon,
    insuranceAgency,
    laundry,
    lawyer,
    locksmith,
    makeupArtist,
    movingCompany,
    nailSalon,
    painter,
    plumber,
    psychic,
    realEstateAgency,
    roofingContractor,
    storage,
    summerCampOrganizer,
    tailor,
    telecommunicationsServiceProvider,
    tourAgency,
    touristInformationCenter,
    travelAgency,
    veterinaryCare,
  ];

  /// Shopping Types: https://developers.google.com/maps/documentation/places/web-service/place-types#shopping
  static const List<PlaceType> shoppingTypes = [
    asianGroceryStore,
    autoPartsStore,
    bicycleStore,
    bookStore,
    butcherShop,
    cellPhoneStore,
    clothingStore,
    convenienceStore,
    departmentStore,
    discountStore,
    electronicsStore,
    foodStore,
    furnitureStore,
    giftShop,
    groceryStore,
    hardwareStore,
    homeGoodsStore,
    homeImprovementStore,
    jewelryStore,
    liquorStore,
    market,
    petStore,
    shoeStore,
    shoppingMall,
    sportingGoodsStore,
    store,
    supermarket,
    warehouseStore,
    wholesaler,
  ];

  /// Sports Types: https://developers.google.com/maps/documentation/places/web-service/place-types#sports
  static const List<PlaceType> sportsTypes = [
    arena,
    athleticField,
    fishingCharter,
    fishingPond,
    fitnessCenter,
    golfCourse,
    gym,
    iceSkatingRink,
    playground,
    skiResort,
    sportsActivityLocation,
    sportsClub,
    sportsCoaching,
    sportsComplex,
    stadium,
    swimmingPool,
  ];

  /// Transportation Types: https://developers.google.com/maps/documentation/places/web-service/place-types#transportation
  static const List<PlaceType> transportationTypes = [
    airport,
    airstrip,
    busStation,
    busStop,
    ferryTerminal,
    heliport,
    internationalAirport,
    lightRailStation,
    parkAndRide,
    subwayStation,
    taxiStand,
    trainStation,
    transitDepot,
    transitStation,
    truckStop,
  ];

  /// Table B values may be returned as part of a Place Autocomplete (New) response.
  /// These types are also supported by includedPrimaryTypes for Place Autocomplete (New) requests.
  /// Documentation: https://developers.google.com/maps/documentation/places/web-service/place-types#table-b
  static const List<PlaceType> tableBTypes = [
    administrativeAreaLevel3,
    administrativeAreaLevel4,
    administrativeAreaLevel5,
    administrativeAreaLevel6,
    administrativeAreaLevel7,
    archipelago,
    colloquialArea,
    continent,
    establishment,
    finance,
    floor,
    food,
    generalContractor,
    geocode,
    health,
    intersection,
    landmark,
    naturalFeature,
    neighborhood,
    placeOfWorship,
    plusCod,
    pointOfInterest,
    political,
    postBox,
    postalCodePrefix,
    postalCodeSuffix,
    postalTown,
    premise,
    room,
    route,
    streetAddress,
    streetNumber,
    sublocality,
    sublocalityLevel1,
    sublocalityLevel2,
    sublocalityLevel3,
    sublocalityLevel4,
    sublocalityLevel5,
    subpremise,
    townSquare,
  ];

  final String name;
  const PlaceType(this.name);

  static PlaceType? valueOf(String name) =>
      PlaceType.values.firstWhereOrNull((value) => value.name == name);
}
