targets:
  # This target is for the new code.
  $default:
    sources:
      - lib/src/new/**
      - pubspec.*
      - $package$
      - lib/$lib$
    builders:
      json_serializable|json_serializable:
        options:
          include_if_null: false
#          create_json_keys: true
        generate_for:
          - '**/filter/*.dart'
          - '**/model/*.dart'
#      copy_with_extension_gen|copy_with_extension_gen:
#        options:
#          skip_fields: true
#        generate_for:
#          - '**/filter/*.dart'
#          - '**/model/*.dart'
      adeptgenerator:
        enabled: true
        options:
          clone_ignore_synthetic: false
          clone_consider_empty_collection_as_null: true
          clone_generate_clone_extension: true
          copy_with_ignore_synthetic: false
          copy_with_allow_nullable: false
          copy_with_consider_empty_collection_as_null: true
          copy_with_include_private_fields: false
          copy_with_avoid_constructor: false
          diff_ignore_synthetic: false
          diff_generate_diff_extension: true
          is_empty_ignore_synthetic: false
          is_empty_include_private_fields: false
      retrofit_generator|retrofit_generator:
        generate_for:
          - '**/service/*.dart'


  # This target is for the legacy code.
  legacy:
    sources:
      - lib/src/legacy/**
    builders:
      json_serializable|json_serializable:
        options:
          include_if_null: false
          field_rename: snake