import 'package:copy_with_extension/copy_with_extension.dart';
import 'package:google_maps_apis/src/new/model/leg.dart';
import 'package:google_maps_apis/src/new/utils/jsonable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'routing_summary.g.dart';

/// The duration and distance from the routing origin to a place in the response,
/// and a second leg from that place to the destination, if requested.
/// Note: Adding routingSummaries in the field mask without also including either
/// the routingParameters.origin parameter or the searchAlongRouteParameters.polyline.encodedPolyline
/// parameter in the request causes an error.
///
/// Documentation: https://developers.google.com/maps/documentation/places/web-service/reference/rest/v1/RoutingSummary
@JsonSerializable()
@CopyWith()
class RoutingSummary extends Jsonable<RoutingSummary> {
  /// The legs of the trip.
  ///
  /// When you calculate travel duration and distance from a set origin, legs
  /// contains a single leg containing the duration and distance from the origin
  /// to the destination. When you do a search along route, legs contains two legs:
  /// one from the origin to place, and one from the place to the destination.
  final List<Leg>? legs;

  /// A link to show directions on Google Maps using the waypoints from the
  /// given routing summary. The route generated by this link is not guaranteed
  /// to be the same as the route used to generate the routing summary.
  /// The link uses information provided in the request, from fields including
  /// routingParameters and searchAlongRouteParameters when applicable,
  /// to generate the directions link.
  final String? directionsUri;

  RoutingSummary({this.legs, this.directionsUri});

  factory RoutingSummary.fromJson(Map<String, dynamic> json) {
    return _$RoutingSummaryFromJson(json);
  }

  @override
  RoutingSummary? fromJsonMap(Map<String, dynamic>? json) =>
      json != null ? RoutingSummary.fromJson(json) : null;

  @override
  Map<String, dynamic> toJson() {
    return _$RoutingSummaryToJson(this);
  }
}
